services:
  perkibe_nginx:
    build:
      dockerfile: nginx.Dockerfile
    depends_on:
      - perkibe_php
    container_name: perkibe_nginx
    ports:
      - 8010:80
    volumes:
      - ./:/var/www/html
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2G"

  perkibe_php:
    build:
      dockerfile: php.Dockerfile
    container_name: perkibe_php
#    volumes:
#      - ./:/var/www/html
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2G"
  perkibe_composer:
    build:
      dockerfile: php.Dockerfile
    container_name: perkibe_composer
#    volumes:
#      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "composer" ]
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
        reservations:
          cpus: "0.1"
          memory: "256M"

  perkibe_artisan:
    build:
      dockerfile: php.Dockerfile
    container_name: perkibe_artisan
#    volumes:
#      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "php", "artisan" ]

  # perkibe_npm:
  #   image: node:current-alpine
  #   container_name: perkibe_npm
  #   volumes:
  #     - ./:/var/www/html
  #   working_dir: /var/www/html
  #   entrypoint: [ "npm" ]