import {
    uniAngleDown,
    uniBell,
    uniClipboardAlt,
    uniCheck,
    uniChart,
    uniCheckCircle,
    uniCreditCard,
    uniDashboard,
    uniDatabaseAlt,
    uniEllipsisH,
    uniFileCheck,
    uniFileGraph,
    uniFilter,
    uniMapPin,
    uniParcel,
    uniPlus,
    uniSetting,
    uniSearch,
    uniTimes,
    uniTrash,
    uniUsersAlt
} from 'vue-unicons/dist/icons'

export default [
    uniAngleDown,
    uniBell,
    uniClipboardAlt,
    uniCheck,
    uniChart,
    uniCreditCard,
    uniCheckCircle,
    uniDashboard,
    uniDatabaseAlt,
    uniEllipsisH,
    uniFileCheck,
    uniFilter,
    uniFileGraph,
    uniMapPin,
    uniParcel,
    uniPlus,
    uniSetting,
    uniSearch,
    uniTimes,
    uniTrash,
    uniUsersAlt
]
